version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: somePassword
    command: postgres -c wal_level=logical
    ports:
      - "5432:5432"
