
version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.3
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker1:
    image: kafka-image-jmx
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 9101:9101
      - 7101:7101
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://130.61.208.192:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: 130.61.208.192
      KAFKA_OPTS: "-javaagent:/usr/app/jmx_prometheus_javaagent-0.15.0.jar=7101:/usr/app/kafka_broker.yml"

  broker2:
    image: kafka-image-jmx
    depends_on:
      - zookeeper
    ports:
      - 9093:9093
      - 9102:9102
      - 7102:7102
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://130.61.208.192:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_JMX_PORT: 9102
      KAFKA_JMX_HOSTNAME: 130.61.208.192
      KAFKA_OPTS: "-javaagent:/usr/app/jmx_prometheus_javaagent-0.15.0.jar=7102:/usr/app/kafka_broker.yml"

  broker3:
    image: kafka-image-jmx
    depends_on:
      - zookeeper
    ports:
      - 9094:9094
      - 9103:9103
      - 7103:7103
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://130.61.208.192:9094
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9094
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_JMX_PORT: 9103
      KAFKA_JMX_HOSTNAME: 130.61.208.192
      KAFKA_OPTS: "-javaagent:/usr/app/jmx_prometheus_javaagent-0.15.0.jar=7103:/usr/app/kafka_broker.yml"

  schema-registry:
    image: confluentinc/cp-schema-registry:7.4.3
    depends_on:
      - broker1
      - broker2
      - broker3
    ports:
      - 8081:8081
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'broker1:9092,broker2:9093,broker3:9094'

  ksqldb-server:
    image: confluentinc/cp-ksqldb-server:7.4.3
    hostname: ksqldb-server
    container_name: ksqldb-server
    depends_on:
      - broker1
      - broker2
      - broker3
    ports:
      - "8088:8088"
    environment:
      KSQL_CONFIG_DIR: "/etc/ksql"
      KSQL_BOOTSTRAP_SERVERS: "broker1:9092,broker2:9093,broker3:9094"
      KSQL_HOST_NAME: ksqldb-server
      KSQL_LISTENERS: "http://0.0.0.0:8088"
      KSQL_CACHE_MAX_BYTES_BUFFERING: 0
      KSQL_KSQL_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      KSQL_KSQL_CONNECT_URL: "http://connect:8083"
      KSQL_KSQL_LOGGING_PROCESSING_TOPIC_REPLICATION_FACTOR: 1
      KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE: 'true'
      KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE: 'true'


  ksqldb-cli:
    image: confluentinc/cp-ksqldb-cli:7.4.3
    container_name: ksqldb-cli
    depends_on:
      - broker1
      - broker2
      - broker3
      - connect
      - ksqldb-server
    entrypoint: /bin/sh
    tty: true



  connect:
    image: confluentinc/cp-kafka-connect:7.4.3
    depends_on:
      - broker1
      - broker2      
      - broker3
    ports:
      - 8083:8083
    environment:
      CONNECT_BOOTSTRAP_SERVERS: 'broker1:9092,broker2:9093,broker3:9094'
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: compose-connect-group
      CONNECT_CONFIG_STORAGE_TOPIC: compose-connect-configs
      CONNECT_OFFSET_STORAGE_TOPIC: compose-connect-offsets
      CONNECT_STATUS_STORAGE_TOPIC: compose-connect-status
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_REST_ADVERTISED_HOST_NAME: 'connect'
      CONNECT_LOG4J_ROOT_LOGLEVEL: 'INFO'

  kafdrop:
    image: obsidiandynamics/kafdrop
    depends_on:
      - broker1
      - broker2
      - broker3
    ports:
      - 9000:9000
    environment:
      KAFKA_BROKERCONNECT: 'broker1:9092,broker2:9093,broker3:9094'


