global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'kafka-brokers'
    static_configs:
      - targets: ['broker1:7071', 'broker2:7072', 'broker3:7073']

